# Generated by Django 4.2.7 on 2024-03-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('take_app', '0002_country_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
    ]
