# Generated by Django 5.0.3 on 2024-04-04 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('take_app', '0004_alter_person_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
