# Generated by Django 5.0.3 on 2024-04-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comment_turn',
            field=models.CharField(default=True, max_length=10),
            preserve_default=False,
        ),
    ]
